### ISSUE TITLE
首页不能完整显示内容，控制台一直有错误

### ISSUE THREAD

**Issue by jasonencode** [33cn/chain33explore#10]
index.js?2396:19 execer name undefined in tx parser valnode
txParser @ index.js?2396:19
TxInfo @ blockAndTxs.js?9a44:77
eval @ blockAndTxs.js?9a44:288
eval @ blockAndTxs.js?9a44:285
eval @ blockAndTxs.js?9a44:253
Promise.then (async)
getBlocksAndTxInfo @ blockAndTxs.js?9a44:234
eval @ home.js?a2df:75
Promise.then (async)
syncBlocksAndTxs @ home.js?a2df:58
mounted @ home.js?a2df:38
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4219
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
patch @ vue.runtime.esm.js?2b0e:6565
Vue._update @ vue.runtime.esm.js?2b0e:3945
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
Watcher @ vue.runtime.esm.js?2b0e:4468
mountComponent @ vue.runtime.esm.js?2b0e:4073
Vue.$mount @ vue.runtime.esm.js?2b0e:8415
eval @ main.js?56d7:78
./src/main.js @ app.js:3362
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:4479
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997
index.js?2396:36 Uncaught (in promise) TypeError: Cannot read property 'transfer' of undefined
    at txParser (index.js?2396:36)
    at new TxInfo (blockAndTxs.js?9a44:77)
    at eval (blockAndTxs.js?9a44:288)
    at Array.map (<anonymous>)
    at eval (blockAndTxs.js?9a44:285)
    at Array.map (<anonymous>)
    at eval (blockAndTxs.js?9a44:253)

**Comment by wenglk** [comment]
> index.js?2396:19 execer name undefined in tx parser valnode
> txParser @ index.js?2396:19
> TxInfo @ blockAndTxs.js?9a44:77
> eval @ blockAndTxs.js?9a44:288
> eval @ blockAndTxs.js?9a44:285
> eval @ blockAndTxs.js?9a44:253
> Promise.then (async)
> getBlocksAndTxInfo @ blockAndTxs.js?9a44:234
> eval @ home.js?a2df:75
> Promise.then (async)
> syncBlocksAndTxs @ home.js?a2df:58
> mounted @ home.js?a2df:38
> invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
> callHook @ vue.runtime.esm.js?2b0e:4219
> insert @ vue.runtime.esm.js?2b0e:3139
> invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
> patch @ vue.runtime.esm.js?2b0e:6565
> Vue._update @ vue.runtime.esm.js?2b0e:3945
> updateComponent @ vue.runtime.esm.js?2b0e:4066
> get @ vue.runtime.esm.js?2b0e:4479
> Watcher @ vue.runtime.esm.js?2b0e:4468
> mountComponent @ vue.runtime.esm.js?2b0e:4073
> Vue.$mount @ vue.runtime.esm.js?2b0e:8415
> eval @ main.js?56d7:78
> ./src/main.js @ app.js:3362
> **webpack_require** @ app.js:854
> fn @ app.js:151
> 1 @ app.js:4479
> **webpack_require** @ app.js:854
> checkDeferredModules @ app.js:46
> (anonymous) @ app.js:994
> (anonymous) @ app.js:997
> index.js?2396:36 Uncaught (in promise) TypeError: Cannot read property 'transfer' of undefined
> at txParser (index.js?2396:36)
> at new TxInfo (blockAndTxs.js?9a44:77)
> at eval (blockAndTxs.js?9a44:288)
> at Array.map ()
> at eval (blockAndTxs.js?9a44:285)
> at Array.map ()
> at eval (blockAndTxs.js?9a44:253)

能否提供一下外网节点地址，还有使用的浏览器？或者截一下页面窗口以及控制台、Network

**Comment by wenglk** [comment]
> index.js?2396:19 execer name undefined in tx parser valnode
> txParser @ index.js?2396:19
> TxInfo @ blockAndTxs.js?9a44:77
> eval @ blockAndTxs.js?9a44:288
> eval @ blockAndTxs.js?9a44:285
> eval @ blockAndTxs.js?9a44:253
> Promise.then (async)
> getBlocksAndTxInfo @ blockAndTxs.js?9a44:234
> eval @ home.js?a2df:75
> Promise.then (async)
> syncBlocksAndTxs @ home.js?a2df:58
> mounted @ home.js?a2df:38
> invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
> callHook @ vue.runtime.esm.js?2b0e:4219
> insert @ vue.runtime.esm.js?2b0e:3139
> invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
> patch @ vue.runtime.esm.js?2b0e:6565
> Vue._update @ vue.runtime.esm.js?2b0e:3945
> updateComponent @ vue.runtime.esm.js?2b0e:4066
> get @ vue.runtime.esm.js?2b0e:4479
> Watcher @ vue.runtime.esm.js?2b0e:4468
> mountComponent @ vue.runtime.esm.js?2b0e:4073
> Vue.$mount @ vue.runtime.esm.js?2b0e:8415
> eval @ main.js?56d7:78
> ./src/main.js @ app.js:3362
> **webpack_require** @ app.js:854
> fn @ app.js:151
> 1 @ app.js:4479
> **webpack_require** @ app.js:854
> checkDeferredModules @ app.js:46
> (anonymous) @ app.js:994
> (anonymous) @ app.js:997
> index.js?2396:36 Uncaught (in promise) TypeError: Cannot read property 'transfer' of undefined
> at txParser (index.js?2396:36)
> at new TxInfo (blockAndTxs.js?9a44:77)
> at eval (blockAndTxs.js?9a44:288)
> at Array.map ()
> at eval (blockAndTxs.js?9a44:285)
> at Array.map ()
> at eval (blockAndTxs.js?9a44:253)

能否提供一下.env文件的配置信息，还有使用的浏览器？或者截一下页面窗口以及控制台、Network请求情况

**Comment by cjango** [comment]
.env  只修改了联盟链节点的服务器地址 。浏览器 chrome ,截图我这上传有点问题

**Comment by jasonencode** [comment]
节点是联盟链
#默认的执行器，主链是token，平行链是user.p.xxx.token
VUE_APP_DEFAULT_EXECER=token
#10 节点地址
VUE_APP_DEFAULT_PROVIDER=http://XXX.XXX:8801

![1595923530636.jpg][1]


  [1]: http://www.cjango.com/usr/uploads/2020/07/3451318716.jpg

**Comment by jasonencode** [comment]
默认节点没有问题，切到联盟链节点就不行了

**Comment by wenglk** [comment]
试一下fix-leagueChain分支，联盟链特殊处理了下

**Comment by wenglk** [comment]
重新拉一下master分支，已修复，联盟链做了兼容处理

**Comment by jasonencode** [comment]
感谢
